services:
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --maxmemory 500mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  response_generator:
    build: ./response_generator
    container_name: response_generator
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8001"

  # Este es el nuevo servicio que reemplaza a tu cache_service HTTP
  consumer_service:
    build: ./consumer_service
    depends_on:
      - redis
      - kafka
      - response_generator
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka:9092
      RESPONSE_GENERATOR_URL: http://response_generator:8001/query
      MAX_RETRIES: 3
    volumes:
      - ./metrics:/app/metrics
    deploy:
      mode: replicated
      replicas: 1 # Aumenta este número para evaluar "Múltiples Consumers"

  traffic_generator:
    build: ./traffic_generator
    container_name: traffic_generator
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "8002:8002"